name: Run Hello Python
on:
  push:
  workflow_dispatch:
  
jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Execute Python script
        run: python Actividad11/act11_print_hello.py
